# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 650)
        MainWindow.setMinimumSize(QtCore.QSize(400, 650))
        MainWindow.setMaximumSize(QtCore.QSize(400, 650))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("color:rgb(255, 0, 0);\n"
"background-color: rgb(85, 255, 127);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.output_labelButton = QtWidgets.QLabel(self.frame)
        self.output_labelButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_labelButton.sizePolicy().hasHeightForWidth())
        self.output_labelButton.setSizePolicy(sizePolicy)
        self.output_labelButton.setMinimumSize(QtCore.QSize(90, 100))
        self.output_labelButton.setStyleSheet("font: 87 40pt \"Arial Black\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: #fff\n"
"")
        self.output_labelButton.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.output_labelButton.setObjectName("output_labelButton")
        self.verticalLayout.addWidget(self.output_labelButton)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_3.setStyleSheet("font: 87 36pt \"Arial Black\";\n"
"background-color: rgb(0, 0, 0);\n"
"background-color: rgb(85, 255, 127);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.clearButton = QtWidgets.QPushButton(self.frame_3)
        self.clearButton.setMinimumSize(QtCore.QSize(80, 100))
        self.clearButton.setStyleSheet("font: 87 36pt \"Arial Black\";\n"
"color: rgb(255, 255, 255)\n"
"")
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout_6.addWidget(self.clearButton)
        self.percentageButton = QtWidgets.QPushButton(self.frame_3)
        self.percentageButton.setMinimumSize(QtCore.QSize(80, 100))
        self.percentageButton.setStyleSheet("font: 87 36pt \"Arial Black\";\n"
"color: rgb(255, 255, 255)\n"
"")
        self.percentageButton.setObjectName("percentageButton")
        self.horizontalLayout_6.addWidget(self.percentageButton)
        self.backspaceButton = QtWidgets.QPushButton(self.frame_3)
        self.backspaceButton.setMinimumSize(QtCore.QSize(80, 100))
        self.backspaceButton.setStyleSheet("font: 87 36pt \"Arial Black\";\n"
"color: rgb(255, 255, 255)\n"
"")
        self.backspaceButton.setObjectName("backspaceButton")
        self.horizontalLayout_6.addWidget(self.backspaceButton)
        self.divisionButton = QtWidgets.QPushButton(self.frame_3)
        self.divisionButton.setMinimumSize(QtCore.QSize(80, 100))
        self.divisionButton.setStyleSheet("font: 87 36pt \"Arial Black\";\n"
"color: rgb(255, 255, 255)\n"
"")
        self.divisionButton.setObjectName("divisionButton")
        self.horizontalLayout_6.addWidget(self.divisionButton)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(90, 110))
        self.frame_2.setMaximumSize(QtCore.QSize(398, 16777215))
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.seteButton = QtWidgets.QPushButton(self.frame_2)
        self.seteButton.setMinimumSize(QtCore.QSize(80, 100))
        self.seteButton.setStyleSheet("font: 87 36pt \"Arial Black\";\n"
"color: rgb(255, 255, 255)\n"
"")
        self.seteButton.setObjectName("seteButton")
        self.horizontalLayout_2.addWidget(self.seteButton)
        self.oitoButton = QtWidgets.QPushButton(self.frame_2)
        self.oitoButton.setMinimumSize(QtCore.QSize(80, 100))
        self.oitoButton.setStyleSheet("font: 87 36pt \"Arial Black\";\n"
"color: rgb(255, 255, 255)\n"
"")
        self.oitoButton.setObjectName("oitoButton")
        self.horizontalLayout_2.addWidget(self.oitoButton)
        self.noveButton = QtWidgets.QPushButton(self.frame_2)
        self.noveButton.setMinimumSize(QtCore.QSize(80, 100))
        self.noveButton.setStyleSheet("font: 87 36pt \"Arial Black\";\n"
"color: rgb(255, 255, 255)\n"
"")
        self.noveButton.setObjectName("noveButton")
        self.horizontalLayout_2.addWidget(self.noveButton)
        self.mutiplicacaoButton = QtWidgets.QPushButton(self.frame_2)
        self.mutiplicacaoButton.setMinimumSize(QtCore.QSize(80, 100))
        self.mutiplicacaoButton.setStyleSheet("font: 87 36pt \"Arial Black\";\n"
"color: rgb(255, 255, 255)\n"
"")
        self.mutiplicacaoButton.setObjectName("mutiplicacaoButton")
        self.horizontalLayout_2.addWidget(self.mutiplicacaoButton)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 130))
        self.frame_4.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"background-color: rgb(85, 255, 127);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.quatroButton = QtWidgets.QPushButton(self.frame_4)
        self.quatroButton.setMinimumSize(QtCore.QSize(90, 100))
        self.quatroButton.setStyleSheet("font: 87 36pt \"Arial Black\";\n"
"color: rgb(255, 255, 255)\n"
"")
        self.quatroButton.setObjectName("quatroButton")
        self.horizontalLayout_3.addWidget(self.quatroButton)
        self.cincoButton = QtWidgets.QPushButton(self.frame_4)
        self.cincoButton.setMinimumSize(QtCore.QSize(90, 100))
        self.cincoButton.setStyleSheet("font: 87 36pt \"Arial Black\";\n"
"color: rgb(255, 255, 255)\n"
"")
        self.cincoButton.setObjectName("cincoButton")
        self.horizontalLayout_3.addWidget(self.cincoButton)
        self.seisButton = QtWidgets.QPushButton(self.frame_4)
        self.seisButton.setMinimumSize(QtCore.QSize(90, 100))
        self.seisButton.setStyleSheet("font: 87 36pt \"Arial Black\";\n"
"color: rgb(255, 255, 255)\n"
"")
        self.seisButton.setObjectName("seisButton")
        self.horizontalLayout_3.addWidget(self.seisButton)
        self.subtracaoButton = QtWidgets.QPushButton(self.frame_4)
        self.subtracaoButton.setMinimumSize(QtCore.QSize(90, 100))
        self.subtracaoButton.setStyleSheet("font: 87 36pt \"Arial Black\";\n"
"color: rgb(255, 255, 255)\n"
"")
        self.subtracaoButton.setObjectName("subtracaoButton")
        self.horizontalLayout_3.addWidget(self.subtracaoButton)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.umButton = QtWidgets.QPushButton(self.frame_5)
        self.umButton.setMinimumSize(QtCore.QSize(80, 100))
        self.umButton.setStyleSheet("font: 87 36pt \"Arial Black\";\n"
"color: rgb(255, 255, 255)\n"
"")
        self.umButton.setObjectName("umButton")
        self.horizontalLayout_4.addWidget(self.umButton)
        self.doisButton = QtWidgets.QPushButton(self.frame_5)
        self.doisButton.setMinimumSize(QtCore.QSize(80, 100))
        self.doisButton.setStyleSheet("font: 87 36pt \"Arial Black\";\n"
"color: rgb(255, 255, 255)\n"
"")
        self.doisButton.setObjectName("doisButton")
        self.horizontalLayout_4.addWidget(self.doisButton)
        self.tresButton = QtWidgets.QPushButton(self.frame_5)
        self.tresButton.setMinimumSize(QtCore.QSize(80, 100))
        self.tresButton.setStyleSheet("font: 87 36pt \"Arial Black\";\n"
"color: rgb(255, 255, 255)\n"
"")
        self.tresButton.setObjectName("tresButton")
        self.horizontalLayout_4.addWidget(self.tresButton)
        self.somaButton = QtWidgets.QPushButton(self.frame_5)
        self.somaButton.setMinimumSize(QtCore.QSize(80, 100))
        self.somaButton.setStyleSheet("font: 87 36pt \"Arial Black\";\n"
"color: rgb(255, 255, 255)\n"
"")
        self.somaButton.setObjectName("somaButton")
        self.horizontalLayout_4.addWidget(self.somaButton)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.zeroButton = QtWidgets.QPushButton(self.frame_6)
        self.zeroButton.setMinimumSize(QtCore.QSize(80, 100))
        self.zeroButton.setStyleSheet("font: 87 36pt \"Arial Black\";\n"
"color: rgb(255, 255, 255)\n"
"")
        self.zeroButton.setObjectName("zeroButton")
        self.horizontalLayout_5.addWidget(self.zeroButton)
        self.maisMenosButton = QtWidgets.QPushButton(self.frame_6)
        self.maisMenosButton.setMinimumSize(QtCore.QSize(80, 100))
        self.maisMenosButton.setStyleSheet("font: 87 36pt \"Arial Black\";\n"
"color: rgb(255, 255, 255)\n"
"")
        self.maisMenosButton.setObjectName("maisMenosButton")
        self.horizontalLayout_5.addWidget(self.maisMenosButton)
        self.pontoButton = QtWidgets.QPushButton(self.frame_6)
        self.pontoButton.setMinimumSize(QtCore.QSize(80, 100))
        self.pontoButton.setStyleSheet("font: 87 36pt \"Arial Black\";\n"
"color: rgb(255, 255, 255)\n"
"")
        self.pontoButton.setObjectName("pontoButton")
        self.horizontalLayout_5.addWidget(self.pontoButton)
        self.igualButton = QtWidgets.QPushButton(self.frame_6)
        self.igualButton.setMinimumSize(QtCore.QSize(80, 100))
        self.igualButton.setStyleSheet("font: 87 36pt \"Arial Black\";\n"
"color: rgb(255, 255, 255)\n"
"")
        self.igualButton.setObjectName("igualButton")
        self.horizontalLayout_5.addWidget(self.igualButton)
        self.verticalLayout.addWidget(self.frame_6)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CalculadoraPython"))
        self.output_labelButton.setText(_translate("MainWindow", "0"))
        self.clearButton.setText(_translate("MainWindow", "AC"))
        self.percentageButton.setText(_translate("MainWindow", "%"))
        self.backspaceButton.setText(_translate("MainWindow", "<<"))
        self.divisionButton.setText(_translate("MainWindow", "/"))
        self.seteButton.setText(_translate("MainWindow", "7"))
        self.oitoButton.setText(_translate("MainWindow", "8"))
        self.noveButton.setText(_translate("MainWindow", "9"))
        self.mutiplicacaoButton.setText(_translate("MainWindow", "*"))
        self.quatroButton.setText(_translate("MainWindow", "4"))
        self.cincoButton.setText(_translate("MainWindow", "5"))
        self.seisButton.setText(_translate("MainWindow", "6"))
        self.subtracaoButton.setText(_translate("MainWindow", "-"))
        self.umButton.setText(_translate("MainWindow", "1"))
        self.doisButton.setText(_translate("MainWindow", "2"))
        self.tresButton.setText(_translate("MainWindow", "3"))
        self.somaButton.setText(_translate("MainWindow", "+"))
        self.zeroButton.setText(_translate("MainWindow", "0"))
        self.maisMenosButton.setText(_translate("MainWindow", "+/-"))
        self.pontoButton.setText(_translate("MainWindow", "."))
        self.igualButton.setText(_translate("MainWindow", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
